name: Build Apps

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build with PyInstaller
        run: |
          pyinstaller --clean `
            --add-data "templates;templates" `
            --add-data "static;static" `
            --hidden-import webview `
            --hidden-import pandas `
            --hidden-import openpyxl `
            --hidden-import numpy `
            --name "Excel处理工具" `
            --noconsole `
            --onefile `
            app.py
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-processor-windows
          path: dist/Excel处理工具.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
          
      - name: Install system dependencies
        run: |
          brew install gettext
          brew link gettext --force
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build with PyInstaller
        run: |
          pyinstaller --clean \
            --add-data "templates:templates" \
            --add-data "static:static" \
            --hidden-import webview \
            --hidden-import pandas \
            --hidden-import openpyxl \
            --hidden-import numpy \
            --name "Excel处理工具" \
            --noconsole \
            --onefile \
            app.py
            
      - name: Create DMG
        run: |
          mkdir -p dist/dmg
          mv "dist/Excel处理工具" "dist/dmg/Excel处理工具"
          chmod +x "dist/dmg/Excel处理工具"
          hdiutil create -volname "Excel处理工具" -srcfolder dist/dmg -ov -format UDZO "dist/Excel处理工具.dmg"
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-processor-macos
          path: |
            dist/Excel处理工具
            dist/Excel处理工具.dmg
