name: Build Apps

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build with PyInstaller
        run: |
          pyinstaller --clean `
            --add-data "templates;templates" `
            --add-data "static;static" `
            --hidden-import webview `
            --hidden-import pandas `
            --hidden-import openpyxl `
            --hidden-import numpy `
            --name "Excel处理工具" `
            --noconsole `
            --onefile `
            app.py
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-processor-windows
          path: dist/Excel处理工具.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install system dependencies
        run: |
          brew update
          brew install gettext
          brew link gettext --force
          export PATH="/usr/local/opt/gettext/bin:$PATH"
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Clean build directories
        run: |
          rm -rf build dist
          
      - name: Build with PyInstaller
        env:
          DYLD_LIBRARY_PATH: /usr/local/opt/gettext/lib
        run: |
          # 构建普通可执行文件
          pyinstaller --clean -y \
            --add-data "templates:templates" \
            --add-data "static:static" \
            --hidden-import webview \
            --hidden-import pandas \
            --hidden-import openpyxl \
            --hidden-import numpy \
            --name "Excel处理工具" \
            --noconsole \
            --onefile \
            app.py
          
          # 清理目录后构建 .app 包
          rm -rf build dist
          pyinstaller --clean -y \
            --add-data "templates:templates" \
            --add-data "static:static" \
            --hidden-import webview \
            --hidden-import pandas \
            --hidden-import openpyxl \
            --hidden-import numpy \
            --name "Excel处理工具" \
            --noconsole \
            --windowed \
            app.py
            
      - name: Prepare artifacts
        run: |
          mkdir -p release
          # 复制可执行文件（如果存在）
          [ -f "dist/Excel处理工具" ] && cp "dist/Excel处理工具" "release/Excel处理工具"
          # 复制 .app 包（如果存在）
          [ -d "dist/Excel处理工具.app" ] && cp -r "dist/Excel处理工具.app" "release/"
          # 设置权限
          [ -f "release/Excel处理工具" ] && chmod +x "release/Excel处理工具"
          [ -d "release/Excel处理工具.app" ] && chmod -R +x "release/Excel处理工具.app"
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-processor-macos
          path: |
            release/Excel处理工具
            release/Excel处理工具.app
